log:
  lava-bucket: true
  water-bucket: false
  item-place: true
  pvp-death: true
  mob-death: false
  other-death: false
  command: true
  chat: true
  join: true
  quit: true
  door-interact: false
  open-container: false
  container-transaction: false
  item-pickup: true
  item-drop: true
  button: false
  teleport: true
  lever: false
  sign-place: false
  sign-break: false
  item-break: false
  flint-steel: false
  block-place: true
  block-break: true
  block-burn: false
  block-fade: false
  block-form: false
  leaf-decay: false
  mushroom-grow: false
  tree-grow: false
  water-flow: false
  lava-flow: true
  explosion: true
  enderman-pickup: false
  enderman-place: false
  entity-kill: false
  other: false
  spawnmob-egg: false
  herochat: false
  entity-modify: false
  block-inhabit: false
  super-pickaxe: false
  worldedit-place: false
  worldedit-break: false
  crop-trample: true
  block-ignite: false
  fallingblock-place: true
  player-water-flow: false
  player-lava-flow: false
general:
  max-lines: 0
  log-item-drops-on-death: false
  cleanse-period: 20m
  cleanse-age: 0
  delete-data-on-rollback: true
  log-ip-addresses: false
  debug: false
  debug-level: low
  max-radius: 0
  give-user-tool: true
  tool-block: '17'
  default-here-radius: 5
  default-tool-command: ''
  check-for-updates: true
  op-permissions: false
  simplify-time: true
  log-delay: 2
  max-write-logs: 5000
mysql:
  hawkeye-table: hawkeye
  port: 3306
  player-table: hawk_players
  username: axluse
  world-table: hawk_worlds
  hostname: localhost
  max-connections: 10
  password: savetebu4726
  database: minecraft
ignore-worlds:
- thisworldisignored
- soisthisone
command-filter:
- /login
- /restartsrv
- /register
- /spawn
block-filter:
- 567
containertransaction-filter:
  chest: true
  doublechest: true
  furnace: true
  dispenser: true
version: 1.6.0
